apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: aws-iam-credentials
initializers:
- name: iam.amazonaws.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    resources:
    - pods
